### ISSUE TITLE
When logged as admin page remains blank....and another severity notice undefined variable: d in receive_notes.php line 55

### ISSUE THREAD

**Issue by referag** [gman-guru/procurement_sys#2]
Waiting for author help and contribution and still studying code to find  solutions.

**issue 1 :** admin log -> page blank
*_issue2: *_ERROR - 2016-02-27 04:05:17 --> Severity: Notice  --> Undefined variable: d D:\xampp\htdocs\procurementSys\application\views\sysviews\procurement\view_receive_notes.php 55
ERROR - 2016-02-27 04:05:17 --> Severity: Notice  --> Trying to get property of non-object

**Comment by timothymunyao** [comment]
Open the database->go to table users->manually change the field value for admin department to administrator

**Comment by danielGithinji** [comment]
Hi guys,
Sorry for the late reply; I have been a little busy. Unfortunately this is a project I have been unable to maintain because I moved on to other things. 
The code is extremely buggy and at the time of pushing this project to github, which was a few years ago, it barely worked. Therefore I am no longer supporting this project. I apologize for any inconveniences.
@Timothy13Munyao thanks for that correction, but unfortunately like I said before I am no longer supporting this project.(If I were to, I would def. update it to current available technologies).
Thank you for taking a look at the project.
